export const getAllPlaces = () => {
  return {
    title: "Where to next?",
    items: [
      {
        card_name: null,
        data: {
          city_id: 57,
          title: "Beijing123",
          sub_title: "303 activities",
          img_url:
            "https://res.klook.com/image/upload/cities/appookvnsxqzzdjjfrvi.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c57-beijing/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "57",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c57-beijing/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "57",
          country_id: "1020",
          object_id: "city_57",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 28,
          title: "Tokyo",
          sub_title: "1233 activities",
          img_url:
            "https://res.klook.com/image/upload/cities/aeaseouqdsq1jsw1wrhz.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c28-tokyo/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "28",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c28-tokyo/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "28",
          country_id: "1012",
          object_id: "city_28",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 4,
          title: "Bangkok",
          sub_title: "688 activities",
          img_url:
            "https://res.klook.com/image/upload/c_crop,h_698,w_3942,x_0,y_832/destination/alkqxuywajyeym2n5p0o.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c4-bangkok/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "4",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c4-bangkok/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "4",
          country_id: "1004",
          object_id: "city_4",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 13,
          title: "Seoul",
          sub_title: "841 activities",
          img_url:
            "https://res.klook.com/image/upload/v1755071540/destination/fkeylpmlpxnivnikzwel.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c13-seoul/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "13",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c13-seoul/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "13",
          country_id: "1010",
          object_id: "city_13",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 33,
          title: "Ho Chi Minh",
          sub_title: "335 activities",
          img_url:
            "https://res.klook.com/image/upload/v1755774167/destination/gqlqs4ff21y4dovesawx.jpg",
          deep_link:
            "https://www.klook.com/en-GB/destination/c33-ho-chi-minh-city/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "33",
            rcmd_code: "Pe_De_Hp",
            link_url:
              "https://www.klook.com/en-GB/destination/c33-ho-chi-minh-city/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "33",
          country_id: "1013",
          object_id: "city_33",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 49,
          title: "Kuala Lumpur",
          sub_title: "209 activities",
          img_url:
            "https://res.klook.com/image/upload/cities/etx5kedfrwr8ujcu3eoi.jpg",
          deep_link:
            "https://www.klook.com/en-GB/destination/c49-kuala-lumpur/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "49",
            rcmd_code: "Pe_De_Hp",
            link_url:
              "https://www.klook.com/en-GB/destination/c49-kuala-lumpur/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "49",
          country_id: "1019",
          object_id: "city_49",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 2,
          title: "Hong Kong",
          sub_title: "548 activities",
          img_url:
            "https://res.klook.com/image/upload/v1755071653/destination/zhpmlliau1yxfhoiinmj.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c2-hong-kong/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "2",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c2-hong-kong/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "2",
          country_id: "364901",
          object_id: "city_2",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 29,
          title: "Osaka",
          sub_title: "400 activities",
          img_url:
            "https://res.klook.com/image/upload/v1755071490/destination/laesg7vcvxkgxsl6achg.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c29-osaka/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "29",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c29-osaka/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "29",
          country_id: "1012",
          object_id: "city_29",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 34,
          title: "Hanoi",
          sub_title: "271 activities",
          img_url:
            "https://res.klook.com/image/upload/cities/pspsl4sadqxl2yfzckrv.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c34-hanoi/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "34",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c34-hanoi/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "34",
          country_id: "1013",
          object_id: "city_34",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 30,
          title: "Kyoto",
          sub_title: "694 activities",
          img_url:
            "https://res.klook.com/image/upload/cities/rapdxiosmnycxgnfvghp.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c30-kyoto/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "30",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c30-kyoto/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "30",
          country_id: "1012",
          object_id: "city_30",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 19,
          title: "Taipei",
          sub_title: "402 activities",
          img_url:
            "https://res.klook.com/image/upload/v1755071443/destination/oqbyvelzvnwmjnv7q3lc.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c19-taipei/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "19",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c19-taipei/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "19",
          country_id: "1014",
          object_id: "city_19",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
      {
        card_name: null,
        data: {
          city_id: 6,
          title: "Singapore",
          sub_title: "699 activities",
          img_url:
            "https://res.klook.com/image/upload/cities/ostdqxobdcoq6ufqgoyl.jpg",
          deep_link: "https://www.klook.com/en-GB/destination/c6-singapore/",
          recommend_reason: "",
          recently_view: false,
        },
        track_info: {
          extra: {
            Type: "Organic",
            destination_id: "6",
            rcmd_code: "Pe_De_Hp",
            link_url: "https://www.klook.com/en-GB/destination/c6-singapore/",
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            recall_type: "a37",
          },
          card_source_type: "destination",
          card_biz_type: "1001",
          city_id: "6",
          country_id: "1015",
          object_id: "city_6",
          sr_data: {
            payload: '{"type":"Organic"}',
            request_id: "1ee4lfh-1k36lv63i-b8WQfe4366398b",
            rcmd_code: "Pe_De_Hp",
            recall_type: "a37",
          },
        },
      },
    ],
    is_hit: true,
    more_title: "See more",
    more_deep_link: "https://www.klook.com/en-GB/destination_list",
    see_more: null,
  };
};
